global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "./alert.rules.yml"

scrape_configs:
  - job_name: 'flavor-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['172.17.0.1:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'flavor-app'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
